services:
  backend:
    build: ./backend
    container_name: airbnb-backend
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000

  frontend-user:
    build: ./frontend-user
    container_name: airbnb-frontend-user
    ports:
      - "4200:80"
    depends_on:
      - backend

  frontend-admin:
    build: ./frontend-admin
    container_name: airbnb-frontend-admin
    ports:
      - "4300:80"
    depends_on:
      - backend


